[package]
name = "hello_world" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Iaroslav <iaroslav.sheptykin@neusta.de>"]

[dependencies]
serde_json = "1.0"
jsonpath_lib = "0.7"
